### ISSUE TITLE
Always getting no results

### ISSUE THREAD

**Issue by abdullah-tayeh** [gdman/sfdx-destruction#2]
Hi,

I am trying to test out this plugin, I have installed it and my sfds-project.json looks like this:
```
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "47.0",
  "plugins": {
    "sfdx-destruction": {
      "enabledByDefault": true,
      "preFile": "",
      "postFile": "manifest/destructiveChangesPost.xml"
    }
  }
}
```

My package.xml is as follows:
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>50.0</version>
</Package>
```

And I have the destructiveChangesPost.xml as:
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Test_Object_Deletion__c</members>
        <name>CustomObject</name>
    </types>
    <version>50.0</version>
</Package>
```

Then I run `sfdx force:source:deploy -x manifest/package.xml` but I always get No results found and my Test_Object_Deletion__c doesn't get deleted. Is there something that I am missing?

I also tried running using environment variables but with the same results.

**Comment by gdman** [comment]
@abdullah-tayeh that looks about right to me.

The only thing I can spot that may be an issue - add `<version>50.0</version>` to `destructiveChangesPost.xml`.

If that doesn't make any difference, please could you provide the command line output? If it's working there should be a line that says `SFDX destructive changes plugin enabled` and then `Adding <name-of-destructive-changes-file> to package`.

**Comment by abdullah-tayeh** [comment]
@gdman thank you for reply, that's interesting, all I'm getting is
`PS C:\Users\AbdullahTayeh\salesforce> sfdx force:source:deploy -x manifest/package.xml`
```
=== Deployed Source
No results found
```

So I guess nothing is hooking in?

**Comment by gdman** [comment]
@abdullah-tayeh Ahhhh, I see what's happening.

It looks like SFDX doesn't think there is anything to deploy because package.xml is empty therefore it doesn't get as far as calling the hook so the plugin never gets involved and a deployment isn't triggered.

If you stick something in package.xml the plugin should work.

Alternatively, if you are only wanting to run deletions sfdx force:source:delete or sfdx force:mdapi:deploy are probably the way to go.

**Comment by abdullah-tayeh** [comment]
I have updated the original post for better clarity, also added <version>50.0</version> to destructiveChangesPost.xml but to no avail...

**Comment by abdullah-tayeh** [comment]
@gdman Oh works like a treat now, thanks!
